# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0004_cookbook_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='categories',
        ),
    ]
