# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0011_auto_20160704_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='user',
        ),
    ]
